exec-once = waybar
exec-once = waybar --config $HOME/dotfiles/.config/waybar/config-left.jsonc
exec-once = hyprpaper
exec-once = systemctl --user start hyprpolkitagent
exec-once = wl-paste --watch cliphist store
exec-once = hypridle


