wallpaper {
    monitor = DP-1
    path = ~/.config/hypr/wallpaper.png
}

wallpaper {
    monitor = DP-2
    path = ~/.config/hypr/wallpaper.png
}

wallpaper {
    monitor = DP-7
    path = ~/.config/hypr/wallpaper-left.png
}

splash = false
