source = ./monitors.conf
source = ./autostart.conf
source = ./environment.conf
source = ./appearance.conf
source = ./input.conf
source = ./keybinds.conf
source = ./workspaces.conf

$terminal = ghostty
$fileManager = dolphin
$menu = rofi -show run
