# See https://wiki.hypr.land/Configuring/Monitors/
#dekstop
monitor=DP-1,2560x1440,0x0, 1
monitor=DP-2, 3840x2160, 2560x0, 1  
monitor=DP-7, 1920x1080, -1080x0, 1, transform, 1

# #laptop
# monitor=eDP-1,1920x1080,0x0, 1
