# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

workspace = 1, monitor:DP-1 #terminal
workspace = 2, monitor:DP-1 #rider
workspace = 3, monitor:DP-1 #browser
workspace = 4, monitor:DP-1 #misc
workspace = 5, monitor:DP-2 #teams
workspace = 6, monitor:DP-2 #?
workspace = 7, monitor:DP-2 #?
workspace = 8, monitor:DP-7 #rider tool windows
workspace = 9, monitor:DP-7 #Dev tools

workspace = 2, rounding:false, gapsout:0, layout:monocle
workspace = 9, layout:monocle

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

windowrule {
  name = move-vivaldi
  match:class = vivaldi-stable
  workspace = 3
}

windowrule {
  name = move-ghostty
  match:class = com.mitchellh.ghostty 
  workspace = 1
}


windowrule {
    name = move-teams
    match:class = teams-for-linux
    workspace = 5
}

windowrule {
    name = move-ytm
    match:class = YouTube Music Desktop App
    workspace = 5
}


#Rider Initial screen
windowrule {
    name = rider-floating-windows
    match:class=^jetbrains-rider
    match:title=^$
    match:float=1
    center=true
    size=1000 700 
}

# Rider Main windows
windowrule {
    name = move-rider
    match:class = jetbrains-rider
    workspace = 2
}

windowrule {
    name = move-rider2
    match:class = jetbrains-rider
    match:title = Welcome to JetBrains Rider
    float=true
    workspace = 2
}

# Rider tool windows → grouped on workspace 9
windowrule {
    name = move-rider-tools
    match:class = jetbrains-rider
    match:title = ^(Debug|Services|Build|Tests|Git|Commit|Run) - .*$
    no_initial_focus = on
    workspace = 9
}

windowrule {
    name = move-ytm
    match:class = YouTube Music Desktop App
    workspace=5
    no_initial_focus=on
}

windowrule {
    name = move-gparted
    match:class = gparted
    workspace=5
    no_initial_focus=on
}

windowrule {
    name = move-bruno
    match:class = bruno
    workspace=4
    no_initial_focus=on
}


windowrule {
    name = move-dev-tools
    match:class = vivaldi-stable
    match:title = ^Developer Tools - .*$
    group=set always
    no_initial_focus=on
    workspace=8
}

# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule {
#     name = no-gaps-wtv1
#     match:float = false
#     match:workspace = w[tv1]
#
#     border_size = 0
#     rounding = 0
# }
#
# windowrule {
#     name = no-gaps-f1
#     match:float = false
#     match:workspace = f[1]
#
#     border_size = 0
#     rounding = 0
# }

