# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 5, monitor:DP-2
workspace = 6, monitor:DP-2
workspace = 7, monitor:DP-2
workspace = 8, monitor:DP-7
workspace = 9, monitor=DP-7

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

windowrule {
  name = move-vivaldi
  match:class = vivaldi-stable
  workspace = 3
}

windowrule {
  name = move-ghostty
  match:class = com.mitchellh.ghostty 
  workspace = 1
}


windowrule {
    name = move-teams
    match:class = teams-for-linux
    workspace = 5
}

windowrule {
    name = move-ytm
    match:class = YouTube Music Desktop App
    workspace = 5
}


#Rider Initial screen
windowrule {
    name = rider-floating-windows
    match:class=^jetbrains-rider
    match:title=^$
    match:float=1
    center=true
    size=1000 700 
}

# Rider Main windows
windowrule {
    name = move-rider
    match:class = jetbrains-rider
    workspace = 2
    group=set always
}

windowrule {
    name = move-rider2
    match:class = jetbrains-rider
    match:title = Welcome to JetBrains Rider
    float=true
    workspace = 2
}

# Rider Floating windows
windowrule{
    name = move-rider-services
    match:class = jetbrains-rider
    match:title = ^Debug - .*$
    group=set always
    no_initial_focus=on
    workspace=9
}

windowrule {
    name = move-rider-debug
    match:class = jetbrains-rider
    match:title = ^Services - .*$
    group=set always
    no_initial_focus=on
    workspace=9
}

windowrule {
    name = move-rider-build
    match:class = jetbrains-rider
    match:title = ^Build - .*$
    group=set always
    no_initial_focus=on
    workspace=9
}

windowrule {
    name = move-rider-run
    match:class = jetbrains-rider
    match:title = ^Run - .*$
    group=set always
    no_initial_focus=on
    workspace=9
}

windowrule {
    name = move-ytm
    match:class = YouTube Music Desktop App
    workspace=special:music
    no_initial_focus=on
}


windowrule {
    name = move-dev-tools
    match:class = vivaldi-stable
    match:title = ^Developer Tools - .*$
    group=set always
    no_initial_focus=on
    workspace=8
}

bind = SUPER, XF86Launch7, exec, ./ridertools.sh


