alias zshconfig="nvim ~/.zshrc"
alias ohmyzsh="nvim ~/.oh-my-zsh"
alias aliasconfig="nvim ~/.oh-my-zsh/custom/aliases.zsh"
alias ghosttyconfig="nvim ~/.config/ghostty/config"
alias ghosttyupdate="cp ~/.config/ghostty/config ~/dotfiles/config"
alias vpn="sudo openvpn --config ~/.config/vpn/OpenVPN/vpnconfig_cert.ovpn&"
alias nvimconfig="cd ~/.config/nvim"

alias hub="cd ~/cargonerds/cargonerds-hub/"
alias jarvis="cd ~/cargonerds/jarvis/"
alias azd="cd ~/cargonerds/docker/azurite/data/"
