alias zshconfig="nvim ~/.zshrc"
alias ohmyzsh="nvim ~/.oh-my-zsh/custom/"
alias aliasconfig="nvim ~/.oh-my-zsh/custom/aliases.zsh"
alias ghosttyconfig="nvim ~/.config/ghostty/config"
alias ghosttyupdate="cp ~/.config/ghostty/config ~/dotfiles/config"
alias vpn="sudo openvpn --config ~/.config/vpnconfig/vpnconfig.ovpn&"
alias nvimconfig="nvim ~/.config/nvim"
alias i3config="nvim ~/.config/i3/config"

alias hub="cd ~/cargonerds/cargonerds-hub/"
alias jarvis="cd ~/cargonerds/jarvis/"
alias reporting="cd ~/cargonerds/reporting/"
alias pm="cd ~/cargonerds/PricingManager/Frontend/"
alias tf="cd ~/cargonerds/cargonerds-hub-infrastructure/terraform/"
alias azd="cd ~/cargonerds/docker/azurite/data/"
alias aspire="cd ~/cargonerds/PricingManager/Backend/PricingManager.Aspire/PricingManager.Aspire.AppHost/"
